optics:
  f_mm: 25.0
  f_number: 2.8
  pixel_size_um: 3.45
  fov_pixels: 32
  n_zernike: 15
  pupil_grid_size: 256

sensor:
  height: 512
  width: 512
  noise_sigma: 0.01

layers:
  num_layers: 12
  min_dist: 0.2
  max_dist: 20.0

training:
  batch_size: 4
  learning_rate: 0.001
  epochs: 100
